name: E2E Run
on:
  workflow_dispatch:
  #schedule:
    # run every 15 min
    #- cron:  '*/15 2-9 * * 1-5'
  #push:
   # branches: [ lngo/run-e2e-1min ]

env:
  testingScope: e2e
  runningEnv: todo #commands (int / prod / preprod)
  currenTest: 1-getting-started

jobs:
  build-cypress-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - id: set-spec-matrix
        run: echo "specs=$(node scripts/readSpectoMatrix.js)" >> $GITHUB_OUTPUT
        env:
          TEST_PATH: 'cypress/${{ env.testingScope }}/${{ env.currenTest }}'
    outputs:
      specs: ${{ steps.set-spec-matrix.outputs.specs }}

  e2e-run:
    timeout-minutes: 10
    needs: [build-cypress-matrix]
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      max-parallel: 64
      matrix:
        config:
          [
            {
              type: 'desktop',
              config: 'viewportWidth=1920,viewportHeight=1080',
            }
          ]
        browser: [chrome]
        specs: ${{ fromJson(needs.build-cypress-matrix.outputs.specs) }}
    
    container: cypress/browsers:node16.5.0-chrome94-ff93
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: false
          headless: true
          browser: ${{ matrix.browser }}
          config: ${{ matrix.config.config }}
          spec: ${{ matrix.specs }}
          env: testingScope=${{ env.testingScope }}
          
#https://dev.to/pthapa1/how-to-run-cypress-tests-in-parallel-in-github-actions-40pj
