name: E2E Run
on:
  workflow_dispatch:
  #schedule:
    # run every 15 min
    #- cron:  '*/15 2-9 * * 1-5'
  #push:
   # branches: [ lngo/run-e2e-1min ]

env:
  testingScope: e2e
  runningEnv: todo #commands (int / prod / preprod)
  currenTest: 1-getting-started

jobs:
  initTest:
    runs-on: ubuntu-latest
    outputs:
      specConfig: ${{ steps.configVar.outputs.specConfig }}
      matrix: ${{ steps.readSpectoMatrix.outputs.matrix }}
    steps:
      - id: configVar
        run: |
          echo "name=specConfig::video=false,baseUrl=https://example.cypress.io/${{ env.runningEnv }}" >> $GITHUB_OUTPUT  
        shell: bash
      - uses: actions/checkout@v4
      # Step to run the JavaScript script to read the Cypress specs matrix
      - name: Read Spec to Matrix
        id: readSpectoMatrix
        run: node scripts/readSpectoMatrix.js
        env:
          TEST_PATH: 'cypress/${{ env.testingScope }}/${{ env.currenTest }}'

  e2e-run:
    timeout-minutes: 10
    needs: [initTest]
    runs-on: ubuntu-latest
    strategy:
      matrix:  ${{ fromJSON(needs.initTest.outputs.matrix) }}
      fail-fast: false
    env:
      specConfig: ${{ needs.initTest.outputs.specConfig }}
    container: cypress/browsers:node16.5.0-chrome94-ff93
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: false
          headless: true
          browser: chrome
          spec: ${{ matrix.specs.spec}}
          env: testingScope=${{ env.testingScope }}
          config: ${{ env.specConfig }}
          
