name: E2E_Run_Basic

on:
  workflow_dispatch:

env:
  testingScope: e2e
  #runningEnv: staging
  currenTest: 1-getting-started

jobs:
  cypress-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: false
          headed: true
          browser: chrome
          spec: cypress/e2e/${{ env.currenTest }}

